// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkMonitor.Infrastructure.Data.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetworkMonitor.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NetworkMonitorDbContext))]
    partial class NetworkMonitorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetworkMonitor.Domain.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("NetworkMonitor.Domain.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Devices_pkey");

                    b.HasIndex("AgentId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("NetworkMonitor.Domain.DeviceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<int>("ScanId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ScanId");

                    b.ToTable("DeviceHistories");
                });

            modelBuilder.Entity("NetworkMonitor.Domain.MonitoringJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("MonitoringJobs_pkey");

                    b.HasIndex("DeviceId");

                    b.ToTable("MonitoringJobs");
                });

            modelBuilder.Entity("NetworkMonitor.Domain.NetworkScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DevicesFound")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.ToTable("NetworkScans");
                });

            modelBuilder.Entity("NetworkMonitor.Domain.RawMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id")
                        .HasName("RawMetrics_pkey");

                    b.HasIndex(new[] { "JobId" }, "IX_Devices_AgentId")
                        .HasDatabaseName("IX_Devices_AgentId1");

                    b.HasIndex(new[] { "JobId", "Timestamp" }, "IX_RawMetrics_JobId_Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("RawMetrics");
                });

            modelBuilder.Entity("NetworkMonitor.Domain.Device", b =>
                {
                    b.HasOne("NetworkMonitor.Domain.Agent", "Agent")
                        .WithMany("Devices")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Devices_Agents");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("NetworkMonitor.Domain.MonitoringJob", b =>
                {
                    b.HasOne("NetworkMonitor.Domain.Device", "Device")
                        .WithMany("MonitoringJobs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Jobs_Devices");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("NetworkMonitor.Domain.RawMetric", b =>
                {
                    b.HasOne("NetworkMonitor.Domain.MonitoringJob", "Job")
                        .WithMany("RawMetrics")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Metrics_Jobs");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("NetworkMonitor.Domain.Agent", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("NetworkMonitor.Domain.Device", b =>
                {
                    b.Navigation("MonitoringJobs");
                });

            modelBuilder.Entity("NetworkMonitor.Domain.MonitoringJob", b =>
                {
                    b.Navigation("RawMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
